name: Run Cypress Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    name: cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          command: npx cypress run --browser chrome --headless
